---
# Clear away margin stuff
reference-location: document
citation-location: document
tbl-cap-location: bottom
cap-location: bottom

format:
    pdf:
      papersize: a4
      documentclass: scrartcl
      # Change page dimensions to fit all
      geometry: 
        # - showframe
        - left=10mm
        - right=10mm
        - top=7mm
        - bottom=7mm
      include-in-header:
        - text: |
            \setlength{\columnsep}{1mm}
            \pagenumbering{gobble}
            \usepackage{amsmath}
            \usepackage{tikz}
            \usetikzlibrary{arrows,shapes}
            \usepackage{.quarto/coffeestains}
---

<!---
Bygg detta dokument med
$ quarto render bat.qmd --to pdf
-->
\coffeestainA{0.55}{0.85}{-25}{50mm}{13mm}

\coffeestainD{0.25}{0.5}{90}{-45mm}{-115mm}

\Begin{multicols}{3}

::: {.callout-tip title="**Lab 7 - Uppg. 5**" icon=false}

**Beräkningar på strömförbrukning i ett batteri.**

| 
| Ett batteri har dessa märkningar:
| 
| U~bat~ \tabto{10mm} = 7.2 V
| E~bat~ \tabto{10mm} = 13 Ah $\cdot$ 7.2 V
|        \tabto{10mm} = 93.6 Wh
| 
| Detta batteripack skall mata tre delsystem:
| 
| U~4G~   \tabto{15mm} = 3.8V
| I~4G~   \tabto{15mm} = 1 A = 1000 mA
| 
| U~WLAN~ \tabto{15mm} = 3.3 V
| I~WLAN~ \tabto{15mm} = 250 mA
| 
| U~CPU~  \tabto{15mm} = 1.8 V
| I~CPU~  \tabto{15mm} = 300 mA

:::



:::: {.callout-note title="**c**" icon=false}

| [***Antagande***]{.underline}: En LD1117 har samma $\eta$ för samma spänningsfall, oavsett vilket U~ut~ som komponenten är specificerad för. 
|
| U~fall~ \tabto{10mm} = U~bat~ - U~CPU~
|         \tabto{10mm} = 7.2 - 1.8
|         \tabto{10mm} = 5.4 V
| 
| Eftersom 3.3V användes under laborationen så är vi intresserade av effektiviteten där.
| 
| U~in~ \tabto{10mm} = U~ut~ + U~fall~
|       \tabto{10mm} = 3.3 + 5.4
|       \tabto{10mm} = 8.7 $\simeq$ 9 V
| 
| Uppmätt under laborationen vid 9V:
| 
| $\eta_{\text{1117}_{\text{5.7}}}$ \tabto{12mm} = 0.36
| t \tabto{12mm} = E~bat~ / \ixx{P}{CPU}{aktiv} $\cdot$ $\eta_{\textnormal{1117}_{\textnormal{5.7}}}$
|   \tabto{12mm} = 93.6 / 0.54 $\cdot$ 0.36
|   \tabto{12mm} = 62.4 h
| 
| Dvs. 2d, 14h, och 24m.

::::



\columnbreak


::: {.callout-tip title="**Svar**" icon=false}

**a**. \ixx{I}{CPU}{max} = 1.186 mA

**b**. t = 173.3 h (7d, 5h, 19m)

**c**. t = 43.3 h (1d, 19h, 20m)

**d**. t = 4134.7h (172d, 6h, 43m)

::: 


::: {.callout-important title="**a**" icon=false}

| Kunden vill att batteriet håller i fem år:
|
| t~krav~ \tabto{10mm} = 5 $\cdot$ 365.25 $\cdot$ 24 h
|         \tabto{10mm} = 43830.0 h
|
| P~4G~   \tabto{10mm} = P~WLAN~ = 0 W
|
| Max-strömmen I~CPU~ fås av:
|
| P = U $\cdot$ I $\rightarrow$ I = P / U
| 
| Givet en tid t så kan vi räkna ut vilken effekt som ett visst batteri kan drivas med:
|
| E = P $\cdot$ t $\rightarrow$ P = E / t
|
|
| Vi vet U, det är U~CPU~ = 1.8 V och att E = E~bat~ = 93.6 Wh.
|
| \ixx{P}{CPU}{max} \tabto{15mm} = E~bat~ / t~krav~
|                   \tabto{15mm} = 93.6 / 43830
|                   \tabto{15mm} = 2.1355 mW
|
| \ixx{I}{CPU}{max} \tabto{15mm} = \ixx{P}{CPU}{max} / U~CPU~
|                   \tabto{15mm} = 2.1355 mW / 1.8 V
|                   \tabto{15mm} = 1.186 mA

:::





::: {.callout-warning title="**b**" icon=false}

$P = U \cdot I$

$P_{CPU_{aktiv}} = U_{CPU} \cdot I_{CPU_{aktiv}}$

$P_{CPU_{aktiv}} = 1.8V \cdot 300 mA$

$P_{CPU_{aktiv}} = 540 mW$

$t = E_{bat}\ /\ P_{CPU_{aktiv}}$

$t = \frac{93.6}{0.54} = 173.3h$

> Dvs. 7 dygn, 5 timmar och 19 minuter.

:::





\columnbreak

::: {.callout-note title="**d -- DENNA LÖSNING ÄR FEL! UPPGIFT ÄNDRAD! GÖR OM!!**" icon=false}

$I_{CPU_{vila}} = 0.1 mA$

> Total förbrukning per tygn:

$E_{vila} + E_{aktiv} =$

$P_{vila} \cdot t_{vila} + P_{aktiv} \cdot t_{aktiv}$


> På ett dygn är det $60 \cdot 24 = 1440$ minuter.

$t_{vila} = 1435m$

$t_{aktiv} = 5m$


> Effekt när systemet är i vila:

$P_{vila} = U_{CPU} \cdot I_{CPU_{vila}}$

$P_{vila} = 1.8 \cdot 0.1 = 0.18 mW$


> Och när systemet är aktivt:

$P_{4G} = 3.8 \cdot 1000 = 3800 mW$

$P_{WLAN} = 3.3 \cdot 250 = 825 mW$

$P_{CPU_{aktiv}} = 1.8 \cdot 300 = 540 mW$

$P_{aktiv} = P_{4G} + P_{WLAN} + P_{CPU_{aktiv}}$

$P_{aktiv} = 5165 mW$

> Detta gör att snitteffekten på ett dygn blir

$P_{snitt} = \frac{P_{aktiv} \cdot t_{aktiv} + P_{vila} \cdot t_{vila}}{t_{total}}$

$P_{snitt} = \frac{5165 \cdot 5 + 0.18 \cdot 1435}{1440}$

$P_{snitt} = 18.11mW$

> Med $E_{bat} = 93.6Wh$ och $\eta = 0.8$ så får vi att

$t = \frac{E_{bat}}{P_{snitt}} \cdot \eta$

$t = \frac{93.6}{0.01811} \cdot 0.8 = 5168.4 \cdot 0.8$

$t = 4134.7h$

> Dvs. 172 dygn, 6 timmar och 43 minuter.

:::


\End{multicols}



